services:
  go-bot:
    image: miku-go-bot
    build:
      context: ..
      dockerfile: docker/go-bot.Dockerfile
    container_name: miku-go-bot
    env_file: ../.env
    environment:
      WORKER_URL: http://py-worker:5005
    volumes:
      - downloads:/data/downloads
    networks:
      - miku_network
    restart: unless-stopped
    depends_on:
      - py-worker

  py-worker:
    image: miku-py-worker
    build:
      context: ..
      dockerfile: docker/py-worker.Dockerfile
    container_name: miku-py-worker
    env_file: ../.env
    environment:
      DOWNLOAD_DIR: /data/downloads
    volumes:
      - downloads:/data/downloads
    ports:
      - "5005:5005"
    networks:
      - miku_network
    restart: unless-stopped

volumes:
  downloads:

networks:
  miku_network:
